apiVersion: v1
kind: Service
metadata:
  name: postgres-service
spec:
  ports:
    - port: 5432
      targetPort: 5432
  selector:
    app: postgres
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
      - name: postgres
        image: postgres:15  # You can specify a specific version here
        env:
        - name: POSTGRES_USER
          value: "postgres_user"  # Set the desired username
        - name: POSTGRES_PASSWORD
          value: "postgres_password"  # Set the desired password
        - name: POSTGRES_DB
          value: "postgres_db"  # Set the desired database name
        ports:
          - containerPort: 5432
        volumeMounts:
          - name: postgres-data
            mountPath: /var/lib/postgresql/data
        resources:
          limits:
            memory: 8Gi
            cpu: 4
          requests:
            cpu: 1
            memory: 8Gi
      volumes:
        - name: postgres-data
          persistentVolumeClaim:
            claimName: postgres-pvc
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 8Gi
