services:
  pgpool:
    image: pgpool/pgpool:latest
    deploy:
      resources:
        limits:
          cpu: "2"
          memory: 8Gi
        requests:
          cpu: "2"
          memory: 8Gi
    container_name: pgpool
    ports:
      - "9999:9999"
    environment:
      POSTGRES_USER: user
      POSTGRES_DB: postgres
      POSTGRES_PASSWORD: password

      # Backend node configurations
      PGPOOL_PARAMS_BACKEND_HOSTNAME0: "10.119.105.102"
      PGPOOL_PARAMS_BACKEND_PORT0: "5432"
      PGPOOL_PARAMS_BACKEND_WEIGHT0: "1"
      PGPOOL_PARAMS_BACKEND_FLAG0: "DISALLOW_TO_FAILOVER"  # Primary node flag

      PGPOOL_PARAMS_BACKEND_HOSTNAME1: "10.119.105.101"
      PGPOOL_PARAMS_BACKEND_PORT1: "5433"
      PGPOOL_PARAMS_BACKEND_WEIGHT1: "1"
      PGPOOL_PARAMS_BACKEND_FLAG1: "ALLOW_TO_FAILOVER"  # Replica node flag

      PGPOOL_PARAMS_BACKEND_HOSTNAME2: "10.119.105.103"
      PGPOOL_PARAMS_BACKEND_PORT2: "5433"
      PGPOOL_PARAMS_BACKEND_WEIGHT2: "1"
      PGPOOL_PARAMS_BACKEND_FLAG2: "ALLOW_TO_FAILOVER"  # Replica node flag

      PGPOOL_PARAMS_BACKEND_HOSTNAME3: "10.119.105.104"
      PGPOOL_PARAMS_BACKEND_PORT3: "5433"
      PGPOOL_PARAMS_BACKEND_WEIGHT3: "1"
      PGPOOL_PARAMS_BACKEND_FLAG3: "ALLOW_TO_FAILOVER"  # Replica node flag

      # Health check
      PGPOOL_PARAMS_HEALTH_CHECK_PERIOD: "30"
      PGPOOL_PARAMS_HEALTH_CHECK_TIMEOUT: "10"
      PGPOOL_PARAMS_HEALTH_CHECK_USER: "user"
      PGPOOL_PARAMS_HEALTH_CHECK_PASSWORD: "password"
