fullnameOverride: "crdb"
single-node: true 

auth:
  enabled: false

insecure: true

statefulset:
  replicas: 1
  resources:
    limits:
      cpu: 4
      memory: 8Gi
    requests:
      cpu: 1
      memory: 8Gi
  securityContext:
    enabled: false
  tls:
    enabled: false
  auth:
    enabled: false
  insecure: true

storage:
  hostPath: ""
  persistentVolume:
    enabled: true
    size: 10Gi
    storageClass: "standard"


tls:
  enable: false

securityContext:
  enabled: false