fullnameOverride: "crdb"
single-node: true 

statefulset:
  replicas: 1
  resources:
    limits:
      cpu: 4
      memory: 8Gi
    requests:
      cpu: 1
      memory: 8Gi
  tls:
    enabled: false

storage:
  hostPath: "D:\Documents\Projects\Uni\TA\CRDBKube_Capstone\crdb"
  persistentVolume:
    enabled: true
    size: 10Gi
    storageClass: "standard"

tls:
  enable: false