apiVersion: batch/v1
kind: Job
metadata:
  name: crdb4-init
  labels:
    app: crdb4
spec:
  template:
    spec:
      containers:
      - name: crdb4-init
        image: cockroachdb/cockroach:v24.3.0
        imagePullPolicy: IfNotPresent
        command:
          - "/cockroach/cockroach"
          - "init"
          - "--insecure"
          - "--host=crdb4-0.cockroachdb"
      restartPolicy: OnFailure