apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: crdb4
spec:
  serviceName: "crdb4"
  replicas: 4
  selector:
    matchLabels:
      app: crdb4
  template:
    metadata:
      labels:
        app: crdb4
    spec:
      tolerations:
        - key: "node-role.kubernetes.io/control-plane"
          operator: "Exists"
          effect: "NoSchedule"
      containers:
        - name: crdb4
          image: cockroachdb/cockroach:v23.1.8
          ports:
            - containerPort: 26257 # SQL Port
              name: db
            - containerPort: 8080  # Admin UI
              name: http
          volumeMounts:
            - name: crdb1-data
              mountPath: /cockroach/cockroach-data
          args:
            - "start"
            - "--join=crdb4-0.cockroachdb.cockroachdb.svc.cluster.local:26257"
            - "--advertise-host=$(HOSTNAME).cockroachdb.cockroachdb.svc.cluster.local"
            - "--http-addr=0.0.0.0:8080"
            - "--insecure"
          resources:
            limits:
              cpu: "2"
              memory: 8Gi
            requests:
              cpu: "1"
              memory: 4Gi
      volumes:
        - name: crdb4-data
          emptyDir: {}
  volumeClaimTemplates:
    - metadata:
        name: crdb4-data
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 10Gi
        storageClassName: manual
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - osing
---
apiVersion: v1
kind: Service
metadata:
  name: crdb4
spec:
  ports:
    - port: 26257
      targetPort: 26257
      name: db
    - port: 8080
      targetPort: 8080
      name: http
  clusterIP: None
  selector:
    app: crdb4
---
apiVersion: v1
kind: Service
metadata:
  name: crdb4-public
spec:
  type: LoadBalancer
  ports:
    - port: 26257
      targetPort: 26257
      name: db
    - port: 8080
      targetPort: 8080
      name: http
  selector:
    app: crdb4