apiVersion: batch/v1
kind: Job
metadata:
  name: cluster-init-1
  labels:
    app: crdb1
spec:
  template:
    spec:
      containers:
      - name: cluster-init
        image: cockroachdb/cockroach:v24.3.0
        imagePullPolicy: IfNotPresent
        command:
          - "/cockroach/cockroach"
          - "init"
          - "--insecure"
          - "--host=crdb1-0.cockroachdb"
      restartPolicy: OnFailure