apiVersion: v1
kind: PersistentVolume
metadata:
  name: psql-node-1 # Name pv 1 for postgresql
spec:
  capacity:
    storage: 15Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: manual
  local:
    path: /kube/data/capstone/psql/main
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - osing # Name Cluster 1
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: psql-replica-2 # Name pv 2 for postgresql
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: manual
  local:
    path: /kube/data/capstone/psql/rplc
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - basring # Name Cluster 2
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: psql-replica-3 # Name pv 3 for postgresql
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: manual
  local:
    path: /kube/data/capstone/psql/rplc
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - pulaumerah # Name Cluster 3
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: psql-replica-4 # Name pv 4 for postgresql
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: manual
  local:
    path: /kube/data/capstone/psql/rplc
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - djawatan # Name Cluster 4