apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgres-pv
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  local:
    # path: "/kube/data/"
  path: "/mnt/d/Documents/Projects/Uni/TA/DG/volumes"
  # hostPath:
  #   path: ""  # Kubernetes uses Unix-style paths; adjust as shown
  # storageClassName: standard
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - postgres
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-pvc
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  # storageClassName: manual
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-deployment
  labels:
    app: postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
      - name: postgres
        image: postgres:15
        ports:
        - containerPort: 5432
        env:
        - name: POSTGRES_USER
          value: "postgres_user"  # Set the desired username
        - name: POSTGRES_PASSWORD
          value: "postgres_password"  # Set the desired password
        - name: POSTGRES_DB
          value: "postgres_db"  # Set the desired database name
        volumeMounts:
        - name: postgres-storage
          # mountPath: "/kube/data/"
          mountPath: "/mnt/d/Documents/Projects/Uni/TA/DG/volumes"
        resources:
          limits:
            cpu: "3"
            memory: 4Gi
          requests:
            cpu: "1"
            memory: 512Mi
      volumes:
      - name: postgres-storage
        persistentVolumeClaim:
          claimName: postgres-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: postgres-service
spec:
  selector:
    app: postgres
  ports:
  - protocol: TCP
    port: 5432
    targetPort: 5432
  type: ClusterIP
