apiVersion: v1
kind: PersistentVolume
metadata:
  name: crdb-1-node-1 # Name pv 1 for cockroach single
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: manual
  local:
    path: /kube/data/capstone/crdb1