apiVersion: v1
kind: PersistentVolume
metadata:
  name: psql-node-1 # Name pv 1 for postgresql
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: manual
  local:
    path: /kube/data/capstone/psql